bin: ebl: fix version sorting code again

diff --git a/bin/ebl b/bin/ebl
--- a/bin/ebl
+++ b/bin/ebl
@@ -62,22 +62,29 @@ then
 	exit 1
 fi
 
+pkgname=$(basename ${pkg})
+
 vers=()
-eblds=()
 for ebl in ${pkg}/*.ebuild
 do
 	ebl_ver=$(echo "${ebl}" | sed 's/.*-\([0-9.]\+\(_[0-9a-z]\+\)\?\(-r[0-9]\+\)\?\).ebuild/\1/')
-	eblds+=(${ebl})
 	vers+=(${ebl_ver})
 done
-if [[ "${#eblds[@]}" -eq 0 || ! -f "${eblds[0]}" ]]
+if [[ "${#vers[@]}" -eq 0 ]]
 then
-	echo "ERROR: .ebuild file not found" 1>&2
+	echo "ERROR: no .ebuild files found" 1>&2
 	exit 1
 fi
-vers_sorted=($(echo ${vers[@]} | sort -V -r))
+
+vers_sorted=($(echo ${vers[@]} | xargs -n 1 | sort -V -r))
 pkgver="${vers_sorted[0]}"
-pkg_ebuild="${eblds[0]}"
+pkg_ebuild="${pkg}/${pkgname}-${pkgver}.ebuild"
+
+if [[ ! -f "${pkg_ebuild}" ]]
+then
+	echo "ERROR: ${pkg_ebuild} file not found" 1>&2
+	exit 1
+fi
 
 TMPDIR=$(bash -c "source ${EP}/etc/portage/make.conf && echo \$PORTAGE_TMPDIR")
 bld_dir="${TMPDIR}/portage/${pkg}-${pkgver}"
