ptools/prefixhelpers: handle TMPDIR=/tmp default on worker nodes

diff --git a/prefix-tools/sh/prefixhelpers b/prefix-tools/sh/prefixhelpers
--- a/prefix-tools/sh/prefixhelpers
+++ b/prefix-tools/sh/prefixhelpers
@@ -279,7 +279,8 @@ function set_tmpdir
 	fi
 
 	# If still not set, then use a default
-	if [[ -z "${THE_TMPDIR}" ]]
+	if [[ -z "${THE_TMPDIR}" || \
+			( "${THE_TMPDIR}" = "/tmp" && "${cluster}" = "olcf-summit" ]]
 	then
 		case "${cluster}" in
 		olcf-summit)
@@ -289,13 +290,19 @@ function set_tmpdir
 			# same FS as the prefix (which is expected to be the
 			# Spectrum parallel FS). Note: for worker machines we
 			# won't get here since RM case above.
-			if [[ -n "${root}" ]]
+			if [[ -z "${LSB_JOBID}" ]]
 			then
-				THE_TMPDIR="${root}"/var/tmp
-			else
-				echo "ERROR: temp dir selection failed: " \
-					"refusing to use /tmp on Summit," \
-					"but prefix path was not given" 1>&2
+				if [[ -n "${root}" ]]
+				then
+					THE_TMPDIR="${root}"/var/tmp
+				else
+					echo "ERROR: temp dir selection failed: " \
+						"refusing to use /tmp on Summit login machine," \
+						"but prefix path was not given" 1>&2
+					exit 1
+				fi
+			else # should have detected the tmp dir set by the RM above
+				echo "ERROR: set_tmpdir: internal logic error: unreachable" 1>&2
 				exit 1
 			fi
 			;;
